---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: clean-node
  labels:
    run: clean-node
spec:
  replicas: 1
  selector:
    matchLabels:
      run: clean-node
  template:
    metadata:
      labels:
        run: clean-node
    spec:
      containers:
      - name: clean-node
        image: romanriazantsev/cloud-infrastructure-hw
        ports:
        - containerPort: 80
          protocol: TCP
